spring:
  application:
    name: BankApp
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/busticketdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect